spring:
  datasource:
    url: jdbc:h2:~/employee_data_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS employee_data_db
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    schema: EMP
    initialization-mode: always
    data: "classpath:import_schema.sql, classpath:import_data.sql"

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.H2Dialect


logging:
  level:
    .: error
    org.springframework: ERROR
    com.amsidh.mvc: INFO
    # Logs the JDBC parameters passed to a query
    org.hibernate:
      SQL: debug
      type: trace
      additivity: false