DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMPID INTEGER NOT NULL AUTO_INCREMENT,
  EMPNAME VARCHAR(250) NOT NULL,
  COMPANY VARCHAR(500) DEFAULT NULL,
  JOINING_DATE TIMESTAMP,
  CONTACT_NUMBER NUMBER NOT NULL,
  EMAILID VARCHAR(250) NOT NULL,
  ADDRESS  VARCHAR(250) NOT NULL,
  PRIMARY KEY (EMPID)
);